"""
Django settings for familycontrol project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# `.env` faylini o'qish (mahalliy ishlash uchun qulaylik).
#
# Railway/Heroku kabi platformalarda muhit o'zgaruvchilari jarayonga to'g'ridan
# to'g'ri beriladi, shuning uchun u yerda `.env` kerak emas va bu qadam
# hech narsani buzmaydi. Mahalliy kompyuterda esa `TELEGRAM_BOT_TOKEN` ni
# `.env` fayliga yozib qo'yish yetarli.
#
# DIQQAT: `.env` hech qachon GitHub'ga yuklanmasin (`.gitignore` da turibdi) —
# uning ichida maxfiy ma'lumotlar bor.
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:
    # python-dotenv o'rnatilmagan bo'lsa muhit o'zgaruvchilaridan foydalaniladi.
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-pcrl#)**v)&!3r6ye*j+691_p7rj7wm9q+sh9*3u_*qp5ou&a^"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["https://familycontrol-production.up.railway.app"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "parental_control",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = "familycontrol.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "familycontrol.wsgi.application"


def _parse_postgres_url(url):
    """`DATABASE_URL` ni Django sozlamalariga bo'laklarga ajratadi.

    Nima uchun `dj-database-url` emas: Neon manzilida `?sslmode=require&
    channel_binding=require` kabi qo'shimcha parametrlar bor. Uchinchi tomon
    kutubxonalari shularni har xil talqin qiladi (ba'zilari tashlab yuboradi).
    Bu yerda barcha o'qilgan parametrlar `OPTIONS` ga to'g'ridan-to'g'ri
    beriladi — `psycopg` ularni to'g'ri taniydi.

    Talqin qilinmagan parametr bo'lsa, uni `options` orqali o'tkazamiz, shunda
    `options=-c%20statement_timeout%3D5000` kabi narsalar ham ishlaydi.
    """
    from urllib.parse import parse_qsl, unquote, urlparse

    parsed = urlparse(url)

    if parsed.scheme not in ("postgres", "postgresql"):
        raise ValueError(
            f"DATABASE_URL sxemasi qo'llab-quvvatlanmaydi: {parsed.scheme!r}. "
            "Kutilgan: postgresql://..."
        )

    options = {}
    for key, value in parse_qsl(parsed.query, keep_blank_values=True):
        # Django/psycopg uchun ma'lum kalitlar
        options[key] = unquote(value)

    # `options` parametri maxsus: -c kalit=qiymat juftligi qo'shish kerak
    raw_options = options.pop("options", None)
    if raw_options:
        for item in raw_options.split():
            if "=" in item:
                name, _, val = item.partition("=")
                existing = options.get(name, "")
                options[name] = f"{existing} {val}" if existing else val

    # `sslrootcert` kabi yo'llar Django uchun to'g'ri emas
    options = {k: v for k, v in options.items() if v != ""}

    if not parsed.username or not parsed.hostname:
        raise ValueError("DATABASE_URL da foydalanuvchi yoki host topilmadi")

    return {
        "name": unquote((parsed.path or "/postgres").lstrip("/")) or "postgres",
        "user": unquote(parsed.username),
        "password": unquote(parsed.password or ""),
        "host": parsed.hostname,
        "port": parsed.port or 5432,
        "options": options,
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL (Neon) ishlatiladi. Manzil `DATABASE_URL` muhit o'zgaruvchisidan
# olinadi — kodga YOZILMAYDI, chunki parol GitHub'ga tushib qolmasligi kerak.
#
# Railway:  Variables -> DATABASE_URL
# Mahalliy: `.env` fayliga yozing (namuna `.env.example` da)
#
# `DATABASE_URL` yo'q bo'lsa SQLite'ga qaytadi — bu qulaylik uchun: mahalliy
# tez sinash uchun server kerak emas.
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if DATABASE_URL:
    _pg = _parse_postgres_url(DATABASE_URL)

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _pg["name"],
            "USER": _pg["user"],
            "PASSWORD": _pg["password"],
            "HOST": _pg["host"],
            "PORT": _pg["port"],
            "OPTIONS": _pg["options"],
            # Neon bergan manzil `-pooler.` bilan tugaydi — bu PgBouncer
            # (transaction rejimi). Unda Django ulashni bo'sh qoldirmasligi
            # kerak: aks holda `SET` buyruqlari keyingi so'rovga ko'tarilib
            # ketadi va "server tomonidan tasodifan uzildi" xatolari chiqadi.
            # Xavfsizlik tezligidan ustun.
            "CONN_MAX_AGE": int(os.environ.get("CONN_MAX_AGE", "0")),
            # So'rov ichidagi bir nechta `save()` bitta tranzaksiyada bo'lishi
            # uchun (pairing kodidan foydalanilmasligi kabi).
            "ATOMIC_REQUESTS": True,
            # Test bazasi oldindan yaratiladi va YO'Q QILINMAYDI.
            #
            # Nega: Neon manzili PgBouncer (transaction rejimi) orqali o'tadi va
            # u o'z havuzida server ulanishlarini ushlab turadi. Django test
            # yakunida `DROP DATABASE` bersa, "database is being accessed by
            # other users" xatosi chiqadi (test `OK` bo'lganiga qaramay).
            #
            # `TEST["KEEP_DB"]` Django tomonidan o'qilMAYDI (u `global_settings.TEST`
            # da yo'q) — shuning uchun `TEST_RUNNER` pastda `keepdb=True` ni
            # avtomatik yoqadi. O'chirish: `TEST_KEEP_DB=0 python manage.py test`
            #
            # BIR MARTA: `python manage.py prepare_test_db`
            "TEST": {
                "NAME": os.environ.get("TEST_DATABASE_NAME", "neondb_test"),
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Test runner: `--keepdb` ni avtomatik yoqadi (Neon/PgBouncer uchun zarur).
# Tafsilot: `familycontrol/test_runner.py`
TEST_RUNNER = "familycontrol.test_runner.FamilyControlTestRunner"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "pair": "5/minute",
        "claim": "10/minute",
    },
}

# Telegram bildirishnomalari uchun bot tokeni.
# DIQQAT: bu qiymat FAQAT serverda bo'lishi kerak. Ilovaga (Flutter/Android)
# hech qachon joylashtirmang — APK ni ochgan har kim tokeni topib oladi.
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}
