# Generated by Django 5.2.17 on 2026-10-03 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_identifier", models.CharField(max_length=255, unique=True)),
                ("device_name", models.CharField(blank=True, max_length=255)),
                (
                    "pairing_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=6, null=True
                    ),
                ),
                (
                    "pairing_code_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "device_token_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("battery_level", models.FloatField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("package_name", models.CharField(max_length=255)),
                ("total_time_in_foreground_ms", models.BigIntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_usage_logs",
                        to="parental_control.childdevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessibilityTextLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("package_name", models.CharField(max_length=255)),
                ("extracted_text", models.TextField()),
                ("context_type", models.CharField(blank=True, max_length=100)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility_text_logs",
                        to="parental_control.childdevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstalledApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("app_name", models.CharField(max_length=255)),
                ("package_name", models.CharField(max_length=255)),
                ("is_blocked", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installed_apps",
                        to="parental_control.childdevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_logs",
                        to="parental_control.childdevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("package_name", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="parental_control.childdevice",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="childdevice",
            index=models.Index(
                fields=["pairing_code"], name="parental_co_pairing_291f9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="childdevice",
            index=models.Index(
                fields=["device_token_hash"], name="parental_co_device__15df80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appusagelog",
            index=models.Index(
                fields=["device", "recorded_at"], name="parental_co_device__610726_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessibilitytextlog",
            index=models.Index(
                fields=["device", "recorded_at"], name="parental_co_device__4de1ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installedapp",
            index=models.Index(
                fields=["device"], name="parental_co_device__e13305_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="installedapp",
            unique_together={("device", "package_name")},
        ),
        migrations.AddIndex(
            model_name="locationlog",
            index=models.Index(
                fields=["device", "recorded_at"], name="parental_co_device__b79c50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["device", "recorded_at"], name="parental_co_device__34c3a8_idx"
            ),
        ),
    ]
