# Generated by Django 5.2.17 on 2026-10-04 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parental_control", "0002_alter_childdevice_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppTimeLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("package_name", models.CharField(max_length=255)),
                ("max_daily_minutes", models.IntegerField()),
                ("block_after_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limits",
                        to="parental_control.childdevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("is_new", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="parental_control.childdevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeoZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("radius_meters", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="parental_control.childdevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SOSAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sos_alerts",
                        to="parental_control.childdevice",
                    ),
                ),
            ],
        ),
    ]
