# Generated by Django 5.2.17 on 2026-10-04 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parental_control", "0003_apptimelimit_contact_geozone_sosalert"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramNotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(blank=True, null=True)),
                ("chat_title", models.CharField(blank=True, max_length=255)),
                ("is_enabled", models.BooleanField(default=False)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_setting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram bildirishnoma sozlamasi",
                "verbose_name_plural": "Telegram bildirishnoma sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="DeviceEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("paired", "Qurilma ulandi"),
                            ("unpaired", "Qurilma uzildi"),
                            ("sos", "SOS signali"),
                            ("battery_low", "Batareya past"),
                            ("admin_disabled", "Himoya o'chirildi"),
                            ("child_mode_enabled", "Farzand rejimi yoqildi"),
                            ("zone_exit", "Xavfsizlik zonasidan chiqdi"),
                        ],
                        max_length=40,
                    ),
                ),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_delivered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="parental_control.childdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "created_at"],
                        name="parental_co_device__abdfab_idx",
                    ),
                    models.Index(
                        fields=["is_delivered", "created_at"],
                        name="parental_co_is_deli_c09604_idx",
                    ),
                ],
            },
        ),
    ]
