# Generated by Django 5.2.17 on 2026-10-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parental_control", "0004_telegramnotificationsetting_deviceevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("paired", "Qurilma ulandi"),
                    ("unpaired", "Qurilma uzildi"),
                    ("sos", "SOS signali"),
                    ("battery_low", "Batareya qullab qolmoqda"),
                    ("admin_disabled", "Himoya o'chirildi"),
                    ("admin_enabled", "Himoya yoqildi"),
                    ("child_mode_enabled", "Farzand rejimi yoqildi"),
                    ("zone_exit", "Xavfsizlik zonasidan chiqdi"),
                    ("app_blocked", "Ilova bloklandi"),
                    ("app_unblocked", "Ilova blokdan chiqarildi"),
                ],
                max_length=40,
            ),
        ),
    ]
