# Generated by Django 5.2.17 on 2026-10-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parental_control", "0005_alter_deviceevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="childdevice",
            name="child_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
