# Generated by Django 5.2.17 on 2026-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parental_control", "0006_childdevice_child_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="geozone",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="geozone",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
