# Generated by Django 5.2.17 on 2026-10-04 13:52

from django.db import migrations


class Migration(migrations.Migration):
    """`AccessibilityTextLog` modelini butunlay o'chirish.

    Nima uchun: bu — ekrandagi matnni (`extracted_text`) saqlash kanali.
    Android ilovasi hech qachon to'ldirmagan (`canRetrieveWindowContent="false"`
    manifestda, `ChildAccessibilityService` faqat Sozlamalar/ilova o'rnatish
    ekranlarini bloklaydi), ya'ni jadval har doim bo'sh turardi.

    O'chirish sababi — o'lik kod xavfi: kelajakda kimdir kanalni "ishga
    tushirsa", bu tizim yashirin kuzatuvga aylanib ketardi. Endi model,
    serializer, `POST /sync/batch/` kaliti va `GET /devices/<id>/accessibility/`
    endpoint'i — hammasi yo'q. `tests_batch.py` buni tekshiradi.

    DIQQAT: `DeleteModel` butun jadvalni YO'Q QILADI. Agar bazada haqiqatan
    ekran matnlari bo'lsa, ular bu migratsiyadan keyin qaytarib bo'lmaydi.
    (Bu tizim hech qachon to'ldirmagan, shuning uchun xavf yo'q.)
    """

    dependencies = [
        ("parental_control", "0007_geozone_latitude_geozone_longitude"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccessibilityTextLog",
        ),
    ]
